
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 03 18:07:46 CET 2013
//----------------------------------------------------

package oblig1parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int INT = 11;
  public static final int PROCEDURE = 9;
  public static final int SEMI = 7;
  public static final int LPAR = 5;
  public static final int STRING_LITERAL = 15;
  public static final int EOF = 0;
  public static final int VAR = 10;
  public static final int PROC = 13;
  public static final int ID = 14;
  public static final int RBRACK = 4;
  public static final int COMMA = 12;
  public static final int error = 1;
  public static final int RPAR = 6;
  public static final int LBRACK = 3;
  public static final int RETURN = 8;
  public static final int CLASS = 2;
}

