
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 05 13:18:29 CET 2013
//----------------------------------------------------

package oblig1parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RBRACK = 4;
  public static final int GEQ = 22;
  public static final int PROCEDURE = 9;
  public static final int AND = 17;
  public static final int CLASS = 2;
  public static final int PLUS = 25;
  public static final int GTR = 21;
  public static final int OR = 18;
  public static final int INT = 11;
  public static final int SEMI = 7;
  public static final int LBRACK = 3;
  public static final int RETURN = 8;
  public static final int ID = 30;
  public static final int EXP = 29;
  public static final int SUB = 26;
  public static final int STRING_LITERAL = 31;
  public static final int STRING = 13;
  public static final int COMMA = 15;
  public static final int FLOAT = 12;
  public static final int MULT = 27;
  public static final int EOF = 0;
  public static final int DIV = 28;
  public static final int error = 1;
  public static final int PROC = 16;
  public static final int EQ = 23;
  public static final int LEQ = 20;
  public static final int BOOL = 14;
  public static final int RPAR = 6;
  public static final int NEQ = 24;
  public static final int VAR = 10;
  public static final int LPAR = 5;
  public static final int LESS = 19;
}

